const universityCourses = [
  // --- المواد المشتركة (Common Courses) ---
  { "major": "مشترك", "courseName": "أخلاقيات الحوسبة وطرق البحث", "courseCode": "3001 عال", "hours": 3 },
  { "major": "مشترك", "courseName": "أساسيات قواعد البيانات", "courseCode": "2511 نال", "hours": 4 },
  { "major": "مشترك", "courseName": "أساسيات هندسة البرمجيات", "courseCode": "2111 هاب", "hours": 3 },
  { "major": "مشترك", "courseName": "إدارة المشاريع الهندسية", "courseCode": "4020 هنع", "hours": 2 },
  { "major": "مشترك", "courseName": "الإحصاء الهندسي", "courseCode": "3201 هنع", "hours": 3 },
  { "major": "مشترك", "courseName": "الإحصاء والاحتمالات", "courseCode": "1050 احص", "hours": 4 },
  { "major": "مشترك", "courseName": "الاقتصاد الهندسي", "courseCode": "4010 هنع", "hours": 2 },
  { "major": "مشترك", "courseName": "التحرير العربي", "courseCode": "103 عرب", "hours": 2 },
  { "major": "مشترك", "courseName": "التصميم المنطقي", "courseCode": "1111 هال", "hours": 4 },
  { "major": "مشترك", "courseName": "التفاعل بين الإنسان والحاسب", "courseCode": "3111 هاب", "hours": 3 },
  { "major": "مشترك", "courseName": "الجبر الخطي", "courseCode": "2220 ريض", "hours": 4 },
  { "major": "مشترك", "courseName": "الجبر والهندسة التحليلية", "courseCode": "1070 ريض", "hours": 4 },
  { "major": "مشترك", "courseName": "الخوارزميات وتراكيب البيانات", "courseCode": "2321 عال", "hours": 3 },
  { "major": "مشترك", "courseName": "الرسم الهندسي", "courseCode": "1011 هنع", "hours": 2 },
  { "major": "مشترك", "courseName": "الرياضيات المتقطعة", "courseCode": "1112 عال", "hours": 4 },
  { "major": "مشترك", "courseName": "الطرائق العددية", "courseCode": "2540 ريض", "hours": 4 },
  { "major": "مشترك", "courseName": "اللغة الإنجليزية العلمية", "courseCode": "1604 نجم", "hours": 6 },
  { "major": "مشترك", "courseName": "المعادلات التفاضلية", "courseCode": "3310 ريض", "hours": 4 },
  { "major": "مشترك", "courseName": "المعادلات التفاضلية (هندسة)", "courseCode": "2040 ريض", "hours": 3 },
  { "major": "مشترك", "courseName": "المهارات اللغوية", "courseCode": "101 عرب", "hours": 2 },
  { "major": "مشترك", "courseName": "الميكانيكا الهندسية (ستاتيكا)", "courseCode": "2100 هنع", "hours": 3 },
  { "major": "مشترك", "courseName": "برمجة الحاسب 1", "courseCode": "1301 عال", "hours": 5 },
  { "major": "مشترك", "courseName": "برمجة الحاسب 2", "courseCode": "2301 عال", "hours": 5 },
  { "major": "مشترك", "courseName": "برمجة تطبيقات الويب", "courseCode": "3821 عال", "hours": 3 },
  { "major": "مشترك", "courseName": "حساب التفاضل", "courseCode": "1050 ريض", "hours": 5 },
  { "major": "مشترك", "courseName": "حساب التكامل", "courseCode": "1060 ريض", "hours": 5 },
  { "major": "مشترك", "courseName": "حساب التفاضل والتكامل (هندسة)", "courseCode": "2030 ريض", "hours": 3 },
  { "major": "مشترك", "courseName": "فيزياء عامة (1)", "courseCode": "1010 فيز", "hours": 6 },
  { "major": "مشترك", "courseName": "فيزياء عامة (2)", "courseCode": "1040 فيز", "hours": 6 },
  { "major": "مشترك", "courseName": "كيمياء عامة (1)", "courseCode": "1010 كيم", "hours": 4 },
  { "major": "مشترك", "courseName": "مقدمة في الذكاء الاصطناعي", "courseCode": "101 عال", "hours": 3 },
  { "major": "مشترك", "courseName": "مهارات الاتصال", "courseCode": "1400 علم", "hours": 2 },
  { "major": "مشترك", "courseName": "مهارات الاستماع والمحادثة", "courseCode": "1230 نجم", "hours": 6 },
  { "major": "مشترك", "courseName": "مهارات الحاسب الآلي", "courseCode": "1400 تقن", "hours": 3 },
  { "major": "مشترك", "courseName": "مهارات القراءة", "courseCode": "1210 نجم", "hours": 6 },
  { "major": "مشترك", "courseName": "مهارات الكتابة", "courseCode": "1220 نجم", "hours": 6 },
  { "major": "مشترك", "courseName": "نظم التشغيل", "courseCode": "3701 عال", "hours": 3 },
  { "major": "مشترك", "courseName": "نظم شبكات الحاسب", "courseCode": "3761 هال", "hours": 3 },

  // --- الهندسة الصناعية (Industrial Engineering) ---
  { "major": "الهندسة الصناعية", "courseName": "أساليب التصنيع 1", "courseCode": "2511 صنع", "hours": 3 },
  { "major": "الهندسة الصناعية", "courseName": "أساليب التصنيع 2", "courseCode": "2521 صنع", "hours": 3 },
  { "major": "الهندسة الصناعية", "courseName": "بحوث العمليات 1", "courseCode": "3211 صنع", "hours": 3 },
  { "major": "الهندسة الصناعية", "courseName": "بحوث العمليات 2", "courseCode": "3221 صنع", "hours": 3 },
  { "major": "الهندسة الصناعية", "courseName": "تخطيط ومراقبة الإنتاج", "courseCode": "4311 صنع", "hours": 3 },
  { "major": "الهندسة الصناعية", "courseName": "تصميم التجارب", "courseCode": "4131 صنع", "hours": 3 },
  { "major": "الهندسة الصناعية", "courseName": "تصميم المنتج والابتكارات", "courseCode": "3601 صنع", "hours": 3 },
  { "major": "الهندسة الصناعية", "courseName": "تصميم المرافق", "courseCode": "3321 صنع", "hours": 3 },
  { "major": "الهندسة الصناعية", "courseName": "تصميم نظم العمل", "courseCode": "3311 صنع", "hours": 3 },
  { "major": "الهندسة الصناعية", "courseName": "ضبط الجودة", "courseCode": "3111 صنع", "hours": 3 },
  { "major": "الهندسة الصناعية", "courseName": "مختبر القياسات الهندسية", "courseCode": "3121 صنع", "hours": 1 },
  { "major": "الهندسة الصناعية", "courseName": "مشروع التخرج 1", "courseCode": "4980 صنع", "hours": 2 },
  { "major": "الهندسة الصناعية", "courseName": "مشروع التخرج 2", "courseCode": "4990 صنع", "hours": 4 },
  { "major": "الهندسة الصناعية", "courseName": "موثوقية النظم والصيانة", "courseCode": "4141 صنع", "hours": 3 },
  { "major": "الهندسة الصناعية", "courseName": "نظم التصنيع", "courseCode": "4611 صنع", "hours": 3 },
  { "major": "الهندسة الصناعية", "courseName": "نظم المحاكاة", "courseCode": "4411 صنع", "hours": 3 },
  { "major": "الهندسة الصناعية", "courseName": "هندسة العوامل البشرية", "courseCode": "3411 صنع", "hours": 3 },

  // --- الهندسة الكهربائية (Electrical Engineering) ---
  { "major": "الهندسة الكهربائية", "courseName": "إلكترونيات القوى", "courseCode": "4420 كهر", "hours": 3 },
  { "major": "الهندسة الكهربائية", "courseName": "إلكترونيات الاتصالات", "courseCode": "4151 كهر", "hours": 3 },
  { "major": "الهندسة الكهربائية", "courseName": "اتصالات الأقمار الصناعية", "courseCode": "4290 كهر", "hours": 3 },
  { "major": "الهندسة الكهربائية", "courseName": "اتصالات الألياف البصرية", "courseCode": "4271 كهر", "hours": 3 },
  { "major": "الهندسة الكهربائية", "courseName": "الاتصالات اللاسلكية", "courseCode": "4260 كهر", "hours": 3 },
  { "major": "الهندسة الكهربائية", "courseName": "الاتصالات الرقمية", "courseCode": "4210 كهر", "hours": 3 },
  { "major": "الهندسة الكهربائية", "courseName": "الآلات الكهربائية", "courseCode": "4430 كهر", "hours": 3 },
  { "major": "الهندسة الكهربائية", "courseName": "الأنظمة الإلكترونية", "courseCode": "4191 كهر", "hours": 3 },
  { "major": "الهندسة الكهربائية", "courseName": "الأنظمة المدمجة", "courseCode": "4511 كهر", "hours": 3 },
  { "major": "الهندسة الكهربائية", "courseName": "الدوائر الإلكترونية 1", "courseCode": "3121 كهر", "hours": 4 },
  { "major": "الهندسة الكهربائية", "courseName": "الدوائر الإلكترونية 2", "courseCode": "3171 كهر", "hours": 4 },
  { "major": "الهندسة الكهربائية", "courseName": "الدوائر الكهربائية 1", "courseCode": "2010 كهر", "hours": 4 },
  { "major": "الهندسة الكهربائية",
    "courseName": "الدوائر الكهربائية 2",
    "courseCode": "2020 كهر",
    "hours": 4
  },
  {
    "major": "الهندسة الكهربائية",
    "courseName": "الكهرومغناطيسية 1",
    "courseCode": "2030 كهر",
    "hours": 3
  },
  {
    "major": "الهندسة الكهربائية",
    "courseName": "الكهرومغناطيسية 2",
    "courseCode": "2041 كهر",
    "hours": 3
  },
  {
    "major": "الهندسة الكهربائية",
    "courseName": "المعالجات الدقيقة والميكروكونترولر",
    "courseCode": "3540 كهر",
    "hours": 3
  },
  {
    "major": "الهندسة الكهربائية",
    "courseName": "المواد الكهربائية",
    "courseCode": "3050 كهر",
    "hours": 3
  },
  {
    "major": "الهندسة الكهربائية",
    "courseName": "تحليل أنظمة القدرة",
    "courseCode": "4410 كهر",
    "hours": 3
  },
  {
    "major": "الهندسة الكهربائية",
    "courseName": "تحليل الإشارات والنظم",
    "courseCode": "3010 كهر",
    "hours": 3
  },
  {
    "major": "الهندسة الكهربائية",
    "courseName": "تحويل الطاقة الكهروميكانيكية",
    "courseCode": "3350 كهر",
    "hours": 3
  },
  {
    "major": "الهندسة الكهربائية",
    "courseName": "حماية أنظمة القوى الكهربائية",
    "courseCode": "4440 كهر",
    "hours": 3
  },
  {
    "major": "الهندسة الكهربائية",
    "courseName": "مبادئ أنظمة القوى الكهربائية",
    "courseCode": "3400 كهر",
    "hours": 3
  },
  {
    "major": "الهندسة الكهربائية",
    "courseName": "مبادئ الاتصالات",
    "courseCode": "3200 كهر",
    "hours": 3
  },
  {
    "major": "الهندسة الكهربائية",
    "courseName": "معالجة الإشارات الرقمية",
    "courseCode": "3240 كهر",
    "hours": 3
  },
  {
    "major": "الهندسة الكهربائية",
    "courseName": "مشروع التخرج 1",
    "courseCode": "4980 كهر",
    "hours": 2
  },
  {
    "major": "الهندسة الكهربائية",
    "courseName": "مشروع التخرج 2",
    "courseCode": "4990 كهر",
    "hours": 4
  },
  {
    "major": "الهندسة الكهربائية",
    "courseName": "نظم التحكم الصناعية",
    "courseCode": "4521 كهر",
    "hours": 3
  },
  {
    "major": "الهندسة الكهربائية",
    "courseName": "هندسة الجهد العالي",
    "courseCode": "4433 كهر",
    "hours": 3
  },

  // --- الهندسة المدنية (Civil Engineering) ---
  { "major": "الهندسة المدنية", "courseName": "أنظمة النقل", "courseCode": "3331 همد", "hours": 3 },
  { "major": "الهندسة المدنية", "courseName": "أنظمة مصادر المياه والصرف الصحي", "courseCode": "4461 همد", "hours": 3 },
  { "major": "الهندسة المدنية", "courseName": "إنشاءات معدنية", "courseCode": "4730 همد", "hours": 3 },
  { "major": "الهندسة المدنية", "courseName": "التحليل الانشائي 1", "courseCode": "3610 همد", "hours": 3 },
  { "major": "الهندسة المدنية", "courseName": "التحليل الانشائي 2", "courseCode": "4610 همد", "hours": 3 },
  { "major": "الهندسة المدنية", "courseName": "الجيولوجيا للمهندسين", "courseCode": "2810 همد", "hours": 2 },
  { "major": "الهندسة المدنية", "courseName": "المساحة", "courseCode": "2311 همد", "hours": 3 },
  { "major": "الهندسة المدنية", "courseName": "الهندسة الجيوتقنية 1", "courseCode": "4830 همد", "hours": 3 },
  { "major": "الهندسة المدنية", "courseName": "الهندسة الجيوتقنية 2", "courseCode": "4850 همد", "hours": 3 },
  { "major": "الهندسة المدنية", "courseName": "الهيدرولوجيا", "courseCode": "3310 همد", "hours": 2 },
  { "major": "الهندسة المدنية", "courseName": "تكنولوجيا الخرسانة ومواد التشييد", "courseCode": "3511 همد", "hours": 3 },
  { "major": "الهندسة المدنية", "courseName": "خرسانة مسلحة 1", "courseCode": "4710 همد", "hours": 3 },
  { "major": "الهندسة المدنية", "courseName": "خرسانة مسلحة 2", "courseCode": "4720 همد", "hours": 3 },
  { "major": "الهندسة المدنية", "courseName": "ميكانيكا الموائع", "courseCode": "3210 همد", "hours": 3 },
  { "major": "الهندسة المدنية", "courseName": "مشروع التخرج 1", "courseCode": "4980 همد", "hours": 2 },
  { "major": "الهندسة المدنية", "courseName": "مشروع التخرج 2", "courseCode": "4990 همد", "hours": 4 },
  { "major": "الهندسة المدنية", "courseName": "هندسة البيئة", "courseCode": "3440 همد", "hours": 2 },
  { "major": "الهندسة المدنية", "courseName": "هندسة المرور", "courseCode": "3330 همد", "hours": 3 },

  // --- الهندسة الميكانيكية (Mechanical Engineering) ---
  { "major": "الهندسة الميكانيكية", "courseName": "القياسات الهندسية", "courseCode": "3170 همك", "hours": 3 },
  { "major": "الهندسة الميكانيكية", "courseName": "التبريد وتكييف الهواء", "courseCode": "4520 همك", "hours": 3 },
  { "major": "الهندسة الميكانيكية", "courseName": "التحكم الآلي", "courseCode": "4700 همك", "hours": 3 },
  { "major": "الهندسة الميكانيكية", "courseName": "التصميم الميكانيكي 1", "courseCode": "3310 همك", "hours": 3 },
  { "major": "الهندسة الميكانيكية", "courseName": "التصميم الميكانيكي 2", "courseCode": "3320 همك", "hours": 3 },
  { "major": "الهندسة الميكانيكية", "courseName": "التوربينات الغازية", "courseCode": "4260 همك", "hours": 3 },
  { "major": "الهندسة الميكانيكية", "courseName": "الديناميكا", "courseCode": "2120 همك", "hours": 3 },
  { "major": "الهندسة الميكانيكية", "courseName": "الديناميكا الحرارية 1", "courseCode": "2210 همك", "hours": 3 },
  { "major": "الهندسة الميكانيكية", "courseName": "الديناميكا الحرارية 2", "courseCode": "3220 همك", "hours": 3 },
  { "major": "الهندسة الميكانيكية", "courseName": "الطاقة الشمسية وتطبيقاتها", "courseCode": "4280 همك", "hours": 3 },
  { "major": "الهندسة الميكانيكية", "courseName": "انتقال الحرارة 1", "courseCode": "3410 همك", "hours": 3 },
  { "major": "الهندسة الميكانيكية", "courseName": "انتقال الحرارة 2", "courseCode": "3420 همك", "hours": 3 },
  { "major": "الهندسة الميكانيكية", "courseName": "علم المواد", "courseCode": "2510 همك", "hours": 3 },
  { "major": "الهندسة الميكانيكية", "courseName": "محطات القوى", "courseCode": "4230 همك", "hours": 3 },
  { "major": "الهندسة الميكانيكية", "courseName": "محركات الاحتراق الداخلي", "courseCode": "4210 همك", "hours": 3 },
  { "major": "الهندسة الميكانيكية", "courseName": "مشروع التخرج 1", "courseCode": "4980 همك", "hours": 2 },
  { "major": "الهندسة الميكانيكية", "courseName": "مشروع التخرج 2", "courseCode": "4990 همك", "hours": 4 },
  { "major": "الهندسة الميكانيكية", "courseName": "مقدمة التصميم الهندسي", "courseCode": "2300 همك", "hours": 2 },
  { "major": "الهندسة الميكانيكية", "courseName": "ميكانيكا الآلات", "courseCode": "3130 همك", "hours": 3 },
  { "major": "الهندسة الميكانيكية", "courseName": "ميكانيكا المواد", "courseCode": "2130 همك", "hours": 3 },
  { "major": "الهندسة الميكانيكية", "courseName": "ميكانيكا الموائع", "courseCode": "3510 همك", "hours": 3 },
  { "major": "الهندسة الميكانيكية", "courseName": "نظرية الآلات", "courseCode": "3140 همك", "hours": 3 },
  { "major": "الهندسة الميكانيكية", "courseName": "اهتزازات ميكانيكية", "courseCode": "4150 همك", "hours": 3 },

  // --- علوم الحاسب (Computer Science) ---
  { "major": "علوم الحاسب", "courseName": "أساسيات الأمن السيبراني", "courseCode": "3801 عال", "hours": 3 },
  { "major": "علوم الحاسب", "courseName": "البرمجة المتقدمة", "courseCode": "4311 عال", "hours": 4 },
  { "major": "علوم الحاسب", "courseName": "الحوسبة البرمجية", "courseCode": "4201 عال", "hours": 4 },
  { "major": "علوم الحاسب", "courseName": "الحوسبة الموزعة والمتوازية", "courseCode": "4841 عال", "hours": 4 },
  { "major": "علوم الحاسب", "courseName": "النظرية الحسابية", "courseCode": "2401 عال", "hours": 4 },
  { "major": "علوم الحاسب", "courseName": "النمذجة والمحاكاة", "courseCode": "4211 عال", "hours": 4 },
  { "major": "علوم الحاسب", "courseName": "تراكيب البيانات", "courseCode": "2311 عال", "hours": 4 },
  { "major": "علوم الحاسب", "courseName": "تصميم وتحليل الخوارزميات", "courseCode": "3401 عال", "hours": 3 },
  { "major": "علوم الحاسب", "courseName": "تعلم الآلة", "courseCode": "4552 عال", "hours": 3 },
  { "major": "علوم الحاسب", "courseName": "لغات البرمجة والمترجمات", "courseCode": "4321 عال", "hours": 4 },
  { "major": "علوم الحاسب", "courseName": "مشروع تخرج 1", "courseCode": "4912 عال", "hours": 3 },
  { "major": "علوم الحاسب", "courseName": "مشروع تخرج 2", "courseCode": "4921 عال", "hours": 3 },
  { "major": "علوم الحاسب", "courseName": "معالجة الصورة الرقمية", "courseCode": "4654 عال", "hours": 3 },
  { "major": "علوم الحاسب", "courseName": "معمارية الحاسب ولغة التجميع", "courseCode": "2471 هال", "hours": 4 },
  { "major": "علوم الحاسب", "courseName": "معمل نظم شبكات الحاسب", "courseCode": "3791 هال", "hours": 1 },

  // --- نظم المعلومات (Information Systems) ---
  { "major": "نظم المعلومات", "courseName": "أخلاقيات واستدامة نظم المعلومات", "courseCode": "4905 نال", "hours": 3 },
  { "major": "نظم المعلومات", "courseName": "أمن الحاسب والمعلومات", "courseCode": "3801 نال", "hours": 4 },
  { "major": "نظم المعلومات", "courseName": "ادارة مشاريع نظم المعلومات", "courseCode": "3641 نال", "hours": 4 },
  { "major": "نظم المعلومات", "courseName": "اساسيات علم البيانات", "courseCode": "4811 نال", "hours": 4 },
  { "major": "نظم المعلومات", "courseName": "اساسیات نظم المعلومات", "courseCode": "2121 نال", "hours": 3 },
  { "major": "نظم المعلومات", "courseName": "استراتيجية وادارة نظم المعلومات", "courseCode": "4601 نال", "hours": 3 },
  { "major": "نظم المعلومات", "courseName": "الاعمال الرقمية", "courseCode": "4241 نال", "hours": 3 },
  { "major": "نظم المعلومات", "courseName": "البرمجة لطلاب نظم المعلومات", "courseCode": "2313 عال", "hours": 4 },
  { "major": "نظم المعلومات", "courseName": "البنية التحتية لتقنية المعلومات", "courseCode": "3761 نال", "hours": 4 },
  { "major": "نظم المعلومات", "courseName": "التحليل الكمي", "courseCode": "3311 نال", "hours": 3 },
  { "major": "نظم المعلومات", "courseName": "التنقيب في البيانات", "courseCode": "4571 نال", "hours": 4 },
  { "major": "نظم المعلومات", "courseName": "تحليل وتصميم النظم", "courseCode": "3611 نال", "hours": 4 },
  { "major": "نظم المعلومات", "courseName": "تطوير تطبيقات الويب والمتنقلة", "courseCode": "4904 نال", "hours": 4 },
  { "major": "نظم المعلومات", "courseName": "مباديء المحاسبة المالية", "courseCode": "103 حسب", "hours": 3 },
  { "major": "نظم المعلومات", "courseName": "مشروع تخرج 1", "courseCode": "4911 نال", "hours": 3 },
  { "major": "نظم المعلومات", "courseName": "مشروع تخرج 2", "courseCode": "4921 نال", "hours": 3 },
  { "major": "نظم المعلومات", "courseName": "نظم ادارة قواعد البيانات", "courseCode": "3511 نال", "hours": 4 },
  { "major": "نظم المعلومات", "courseName": "نظم تخطيط موارد المؤسسات", "courseCode": "4201 نال", "hours": 3 },

  // --- هندسة البرمجيات (Software Engineering) ---
  { "major": "هندسة البرمجيات", "courseName": "إدارة مشاريع البرمجيات", "courseCode": "4231 هاب", "hours": 3 },
  { "major": "هندسة البرمجيات", "courseName": "إنشاء البرمجيات", "courseCode": "4111 هاب", "hours": 3 },
  { "major": "هندسة البرمجيات", "courseName": "تحليل متطلبات البرمجيات", "courseCode": "3121 هاب", "hours": 3 },
  { "major": "هندسة البرمجيات", "courseName": "تصميم ومعمارية البرمجيات", "courseCode": "3201 هاب", "hours": 3 },
  { "major": "هندسة البرمجيات", "courseName": "تطوير البرمجيات الآمنة", "courseCode": "3801 هاب", "hours": 3 },
  { "major": "هندسة البرمجيات", "courseName": "تطوير تطبيقات الاجهزة المتنقلة", "courseCode": "4831 عال", "hours": 4 },
  { "major": "هندسة البرمجيات", "courseName": "تنظيم وتصميم الحاسب", "courseCode": "2401 هال", "hours": 3 },
  { "major": "هندسة البرمجيات", "courseName": "ضمان جودة البرمجيات", "courseCode": "4221 هاب", "hours": 3 },
  { "major": "هندسة البرمجيات", "courseName": "مشروع تخرج 1", "courseCode": "4911 هاب", "hours": 3 },
  { "major": "هندسة البرمجيات", "courseName": "مشروع تخرج 2", "courseCode": "4921 هاب", "hours": 3 },

  // --- هندسة الحاسب (Computer Engineering) ---
  { "major": "هندسة الحاسب", "courseName": "أمن الحاسبات والشبكات", "courseCode": "4711 هال", "hours": 3 },
  { "major": "هندسة الحاسب", "courseName": "أنظمة التحكم", "courseCode": "3541 هال", "hours": 3 },
  { "major": "هندسة الحاسب", "courseName": "أنظمة المعالجات الدقيقة", "courseCode": "3411 هال", "hours": 3 },
  { "major": "هندسة الحاسب", "courseName": "الدوائر الإلكترونية", "courseCode": "3501 هال", "hours": 4 },
  { "major": "هندسة الحاسب", "courseName": "الدوائر الكهربائية", "courseCode": "2501 هال", "hours": 4 },
  { "major": "هندسة الحاسب", "courseName": "الروبوتية والأتمتة", "courseCode": "4801 هال", "hours": 3 },
  { "major": "هندسة الحاسب", "courseName": "تحليل الإشارات والنظم", "courseCode": "3520 هال", "hours": 3 },
  { "major": "هندسة الحاسب", "courseName": "تراسل البيانات", "courseCode": "3701 هال", "hours": 3 },
  { "major": "هندسة الحاسب", "courseName": "تصميم أنظمة الدوائر المتكاملة", "courseCode": "4501 هال", "hours": 3 },
  { "major": "هندسة الحاسب", "courseName": "تصميم الأنظمة الرقمية", "courseCode": "360 هال", "hours": 4 },
  { "major": "هندسة الحاسب", "courseName": "تصميم الأنظمة المضمنة", "courseCode": "3631 هال", "hours": 3 },
  { "major": "هندسة الحاسب", "courseName": "تنظيم وعمارة الحاسب", "courseCode": "2411 هال", "hours": 3 },
  { "major": "هندسة الحاسب", "courseName": "شبكات الحاسب", "courseCode": "3711 هال", "hours": 3 },
  { "major": "هندسة الحاسب", "courseName": "مشروع تخرج 1", "courseCode": "4910 هال", "hours": 2 },
  { "major": "هندسة الحاسب", "courseName": "مشروع تخرج 2", "courseCode": "4921 هال", "hours": 4 },
  { "major": "هندسة الحاسب", "courseName": "معمل أنظمة التحكم", "courseCode": "3551 هال", "hours": 1 },
  { "major": "هندسة الحاسب", "courseName": "معمل التصميم المنطقي", "courseCode": "2121 هال", "hours": 1 },
  { "major": "هندسة الحاسب", "courseName": "معمل الدوائر الإلكترونية", "courseCode": "3510 هال", "hours": 1 },
  { "major": "هندسة الحاسب", "courseName": "معمل الدوائر الكهربائية", "courseCode": "2511 هال", "hours": 1 },
  { "major": "هندسة الحاسب", "courseName": "معمل شبكات الحاسب", "courseCode": "3721 هال", "hours": 1 },
  { "major": "هندسة الحاسب", "courseName": "نظرية الأعداد", "courseCode": "3270 هال", "hours": 3 },
  { "major": "هندسة الحاسب", "courseName": "هندسة النظم وإدارة المشاريع", "courseCode": "3611 هال", "hours": 3 }
];
