const universityCourses = [
  // --- المواد المشتركة (Common Courses) ---
  { "major": "مشترك", "courseName": "أخلاقيات الحوسبة", "courseCode": "3001 عال", "hours": 3 },
  { "major": "مشترك", "courseName": "أساسيات قواعد البيانات", "courseCode": "2511 نال", "hours": 4 },
  { "major": "مشترك", "courseName": "أساسيات هندسة البرمجيات", "courseCode": "2111 هاب", "hours": 3 },
  { "major": "مشترك", "courseName": "الإحصاء والاحتمالات", "courseCode": "1050 احص", "hours": 4 },
  { "major": "مشترك", "courseName": "التحرير العربي", "courseCode": "103 عرب", "hours": 2 },
  { "major": "مشترك", "courseName": "التصميم المنطقي", "courseCode": "1111 هال", "hours": 4 },
  { "major": "مشترك", "courseName": "التفاعل بين الإنسان والحاسب", "courseCode": "3111 هاب", "hours": 3 },
  { "major": "مشترك", "courseName": "الجبر الخطي", "courseCode": "2220 ريض", "hours": 4 },
  { "major": "مشترك", "courseName": "الخوارزميات وتراكيب البيانات", "courseCode": "2321 عال", "hours": 3 },
  { "major": "مشترك", "courseName": "الرياضيات المتقطعة", "courseCode": "1112 عال", "hours": 4 },
  { "major": "مشترك", "courseName": "الطرائق العددية", "courseCode": "2540 ريض", "hours": 4 },
  { "major": "مشترك", "courseName": "المعادلات التفاضلية", "courseCode": "3310 ريض", "hours": 4 },
  { "major": "مشترك", "courseName": "برمجة الحاسب 1", "courseCode": "1301 عال", "hours": 5 },
  { "major": "مشترك", "courseName": "برمجة الحاسب 2", "courseCode": "2301 عال", "hours": 5 },
  { "major": "مشترك", "courseName": "برمجة تطبيقات الويب", "courseCode": "3821 عال", "hours": 3 },
  { "major": "مشترك", "courseName": "حساب التفاضل", "courseCode": "1050 ريض", "hours": 5 },
  { "major": "مشترك", "courseName": "حساب التكامل", "courseCode": "1060 ريض", "hours": 5 },
  { "major": "مشترك", "courseName": "فيزياء عامة (1)", "courseCode": "1010 فيز", "hours": 5 },
  { "major": "مشترك", "courseName": "فيزياء عامة (2)", "courseCode": "1040 فيز", "hours": 5 },
  { "major": "مشترك", "courseName": "مقدمة في الذكاء الاصطناعي", "courseCode": "101 عال", "hours": 3 },
  { "major": "مشترك", "courseName": "نظم التشغيل", "courseCode": "3701 عال", "hours": 3 },
  { "major": "مشترك", "courseName": "نظم شبكات الحاسب", "courseCode": "3761 هال", "hours": 3 },

  // --- علوم الحاسب (Computer Science) ---
  { "major": "علوم الحاسب", "courseName": "أساسيات الأمن السيبراني", "courseCode": "3801 عال", "hours": 3 },
  { "major": "علوم الحاسب", "courseName": "البرمجة المتقدمة", "courseCode": "4311 عال", "hours": 4 },
  { "major": "علوم الحاسب", "courseName": "الحوسبة البرمجية", "courseCode": "4201 عال", "hours": 4 },
  { "major": "علوم الحاسب", "courseName": "الحوسبة الموزعة والمتوازية", "courseCode": "4841 عال", "hours": 4 },
  { "major": "علوم الحاسب", "courseName": "اللغة الإنجليزية العلمية", "courseCode": "1604 نجم", "hours": 6 },
  { "major": "علوم الحاسب", "courseName": "المهارات اللغوية", "courseCode": "101 عرب", "hours": 2 },
  { "major": "علوم الحاسب", "courseName": "النظرية الحسابية", "courseCode": "2401 عال", "hours": 4 },
  { "major": "علوم الحاسب", "courseName": "النمذجة والمحاكاة", "courseCode": "4211 عال", "hours": 4 },
  { "major": "علوم الحاسب", "courseName": "تراكيب البيانات", "courseCode": "2311 عال", "hours": 4 },
  { "major": "علوم الحاسب", "courseName": "تصميم وتحليل الخوارزميات", "courseCode": "3401 عال", "hours": 3 },
  { "major": "علوم الحاسب", "courseName": "تعلم الآلة", "courseCode": "4552 عال", "hours": 3 },
  { "major": "علوم الحاسب", "courseName": "لغات البرمجة والمترجمات", "courseCode": "4321 عال", "hours": 4 },
  { "major": "علوم الحاسب", "courseName": "مشروع تخرج 1", "courseCode": "4912 عال", "hours": 3 },
  { "major": "علوم الحاسب", "courseName": "مشروع تخرج 2", "courseCode": "4921 عال", "hours": 3 },
  { "major": "علوم الحاسب", "courseName": "معالجة الصورة الرقمية", "courseCode": "4654 عال", "hours": 3 },
  { "major": "علوم الحاسب", "courseName": "معمارية الحاسب ولغة التجميع", "courseCode": "2471 هال", "hours": 3 },
  { "major": "علوم الحاسب", "courseName": "معمل نظم شبكات الحاسب", "courseCode": "3791 هال", "hours": 1 },
  { "major": "علوم الحاسب", "courseName": "مهارات الاتصال", "courseCode": "1400 علم", "hours": 2 },
  { "major": "علوم الحاسب", "courseName": "مهارات الاستماع والمحادثة", "courseCode": "1230 نجم", "hours": 6 },
  { "major": "علوم الحاسب", "courseName": "مهارات القراءة", "courseCode": "1210 نجم", "hours": 6 },
  { "major": "علوم الحاسب", "courseName": "مهارات الكتابة", "courseCode": "1220 نجم", "hours": 6 },

  // --- نظم المعلومات (Information Systems) ---
  { "major": "نظم المعلومات", "courseName": "أخلاقيات واستدامة نظم المعلومات", "courseCode": "4905 نال", "hours": 3 },
  { "major": "نظم المعلومات", "courseName": "أساسيات علم البيانات", "courseCode": "4811 نال", "hours": 4 },
  { "major": "نظم المعلومات", "courseName": "أساسيات نظم المعلومات", "courseCode": "2121 نال", "hours": 3 },
  { "major": "نظم المعلومات", "courseName": "أمن الحاسب والمعلومات", "courseCode": "3801 نال", "hours": 4 },
  { "major": "نظم المعلومات", "courseName": "إدارة مشاريع نظم المعلومات", "courseCode": "3641 نال", "hours": 4 },
  { "major": "نظم المعلومات", "courseName": "استراتيجية وإدارة نظم المعلومات", "courseCode": "4601 نال", "hours": 3 },
  { "major": "نظم المعلومات", "courseName": "الأعمال الرقمية", "courseCode": "4241 نال", "hours": 3 },
  { "major": "نظم المعلومات", "courseName": "البرمجة لطلاب نظم المعلومات", "courseCode": "2313 عال", "hours": 4 },
  { "major": "نظم المعلومات", "courseName": "البنية التحتية لتقنية المعلومات", "courseCode": "3761 نال", "hours": 4 },
  { "major": "نظم المعلومات", "courseName": "التحليل الكمي", "courseCode": "3311 نال", "hours": 3 },
  { "major": "نظم المعلومات", "courseName": "التنقيب في البيانات", "courseCode": "4571 نال", "hours": 4 },
  { "major": "نظم المعلومات", "courseName": "تحليل وتصميم النظم", "courseCode": "3611 نال", "hours": 4 },
  { "major": "نظم المعلومات", "courseName": "تطوير تطبيقات الويب والمتنقلة", "courseCode": "4904 نال", "hours": 4 },
  { "major": "نظم المعلومات", "courseName": "مبادئ المحاسبة المالية", "courseCode": "103 حسب", "hours": 3 },
  { "major": "نظم المعلومات", "courseName": "مشروع تخرج 1", "courseCode": "4911 نال", "hours": 3 },
  { "major": "نظم المعلومات", "courseName": "مشروع تخرج 2", "courseCode": "4921 نال", "hours": 3 },
  { "major": "نظم المعلومات", "courseName": "نظم إدارة قواعد البيانات", "courseCode": "3511 نال", "hours": 4 },
  { "major": "نظم المعلومات", "courseName": "نظم تخطيط موارد المؤسسات", "courseCode": "4201 نال", "hours": 3 },

  // --- هندسة البرمجيات (Software Engineering) ---
  { "major": "هندسة البرمجيات", "courseName": "إدارة مشاريع البرمجيات", "courseCode": "4231 هاب", "hours": 3 },
  { "major": "هندسة البرمجيات", "courseName": "إنشاء البرمجيات", "courseCode": "4111 هاب", "hours": 3 },
  { "major": "هندسة البرمجيات", "courseName": "تحليل متطلبات البرمجيات", "courseCode": "3121 هاب", "hours": 3 },
  { "major": "هندسة البرمجيات", "courseName": "تصميم ومعمارية البرمجيات", "courseCode": "3201 هاب", "hours": 3 },
  { "major": "هندسة البرمجيات", "courseName": "تطوير البرمجيات الآمنة", "courseCode": "3801 هاب", "hours": 3 },
  { "major": "هندسة البرمجيات", "courseName": "تطوير تطبيقات الأجهزة المتنقلة", "courseCode": "4831 عال", "hours": 4 },
  { "major": "هندسة البرمجيات", "courseName": "تنظيم وتصميم الحاسب", "courseCode": "2401 هال", "hours": 3 },
  { "major": "هندسة البرمجيات", "courseName": "ضمان جودة البرمجيات", "courseCode": "4221 هاب", "hours": 3 },
  { "major": "هندسة البرمجيات", "courseName": "مشروع تخرج 1", "courseCode": "4911 هاب", "hours": 3 },
  { "major": "هندسة البرمجيات", "courseName": "مشروع تخرج 2", "courseCode": "4921 هاب", "hours": 3 },

  // --- هندسة الحاسب (Computer Engineering) ---
  { "major": "هندسة الحاسب", "courseName": "أمن الحاسبات والشبكات", "courseCode": "4711 هال", "hours": 3 },
  { "major": "هندسة الحاسب", "courseName": "أنظمة التحكم", "courseCode": "3541 هال", "hours": 3 },
  { "major": "هندسة الحاسب", "courseName": "أنظمة المعالجات الدقيقة", "courseCode": "3411 هال", "hours": 3 },
  { "major": "هندسة الحاسب", "courseName": "الدوائر الإلكترونية", "courseCode": "3501 هال", "hours": 4 },
  { "major": "هندسة الحاسب", "courseName": "الدوائر الكهربائية", "courseCode": "2501 هال", "hours": 4 },
  { "major": "هندسة الحاسب", "courseName": "الروبوتية والأتمتة", "courseCode": "4801 هال", "hours": 3 },
  { "major": "هندسة الحاسب", "courseName": "تحليل الإشارات والنظم", "courseCode": "3520 هال", "hours": 3 },
  { "major": "هندسة الحاسب", "courseName": "تراسل البيانات", "courseCode": "3701 هال", "hours": 3 },
  { "major": "هندسة الحاسب", "courseName": "تصميم أنظمة الدوائر المتكاملة", "courseCode": "4501 هال", "hours": 3 },
  { "major": "هندسة الحاسب", "courseName": "تصميم الأنظمة الرقمية", "courseCode": "360 هال", "hours": 4 },
  { "major": "هندسة الحاسب", "courseName": "تصميم الأنظمة المضمنة", "courseCode": "3631 هال", "hours": 3 },
  { "major": "هندسة الحاسب", "courseName": "تنظيم وعمارة الحاسب", "courseCode": "2411 هال", "hours": 3 },
  { "major": "هندسة الحاسب", "courseName": "شبكات الحاسب", "courseCode": "3711 هال", "hours": 3 },
  { "major": "هندسة الحاسب", "courseName": "مشروع التخرج 1", "courseCode": "4910 هال", "hours": 2 },
  { "major": "هندسة الحاسب", "courseName": "مشروع التخرج 2", "courseCode": "4921 هال", "hours": 4 },
  { "major": "هندسة الحاسب", "courseName": "معمل أنظمة التحكم", "courseCode": "3551 هال", "hours": 1 },
  { "major": "هندسة الحاسب", "courseName": "معمل التصميم المنطقي", "courseCode": "2121 هال", "hours": 1 },
  { "major": "هندسة الحاسب", "courseName": "معمل الدوائر الإلكترونية", "courseCode": "3510 هال", "hours": 1 },
  { "major": "هندسة الحاسب", "courseName": "معمل الدوائر الكهربائية", "courseCode": "2511 هال", "hours": 1 },
  { "major": "هندسة الحاسب", "courseName": "معمل شبكات الحاسب", "courseCode": "3721 هال", "hours": 1 },
  { "major": "هندسة الحاسب", "courseName": "نظرية الأعداد", "courseCode": "3270 هال", "hours": 3 },
  { "major": "هندسة الحاسب", "courseName": "هندسة النظم وإدارة المشاريع", "courseCode": "3611 هال", "hours": 3 }
];